[config]
manifest_version = "0.0.1"
original_author_user = "darylcecile"

[[setup-script]]
name = "Move zen config to its place"
command = "mkdir -p ~/.config && cp -r zen.toml ~/.config/zen.toml"

[[setup-script]]

[[dependency]]
name = "bat"
installer = "brew"
check = "bat --version"

[[dependency]]
name = "oven-sh/bun/bun"
installer = "brew"
check = "bun --version"

[[dependency]]
name = "powerlevel10k"
installer = "brew"
check = "p10k --version"

[[dependency]]
name = "jandedobbeleer/oh-my-posh/oh-my-posh"
installer = "brew"

[[dependency]]
name = "gh"
installer = "brew"
check = "gh --version"

